# YAML configuration file for Docker Compose version 3.8
version: '3.8'

# Define services
services:

  # Backend service
  backend:
    build: .  # Build the Docker image using the Dockerfile in the current directory
    ports:
      - "3000:3000"  # Forward the container's port 3333 to the host machine's port 3333 for accessing the backend service
    env_file:
      - .env  # Load environment variables from the .env file in the current directory